<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <DebugSymbols>true</DebugSymbols>
    <DebugType>embedded</DebugType>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsPackable>true</IsPackable>
    <NoDefaultLaunchSettingsFile>true</NoDefaultLaunchSettingsFile>
    <Nullable>enable</Nullable>
    <OutputType>Library</OutputType>
    <StaticWebAssetsEnabled>false</StaticWebAssetsEnabled>
    <TargetFramework>net9.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SkySoft.DnsServer.BL\SkySoft.DnsServer.BL.csproj" />
  </ItemGroup>

</Project>
