//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkySoft.Software.FSM {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SkySoft.Software.FSM.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caller {0} has no permissions for {3} transition execution defined inside {2} use case of {1} driver.
        /// </summary>
        internal static string CallerNotAllowedErrorMessageFormatString {
            get {
                return ResourceManager.GetString("CallerNotAllowedErrorMessageFormatString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The number of claim types is not equal to the number of request handlers.
        /// </summary>
        internal static string ClaimTypesUsageCorrectnessErrorMessage {
            get {
                return ResourceManager.GetString("ClaimTypesUsageCorrectnessErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} final state not found in {1} final states.
        /// </summary>
        internal static string FinalStateNotFoundInFinalStates {
            get {
                return ResourceManager.GetString("FinalStateNotFoundInFinalStates", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Final states {0} count not equal use case {1} count.
        /// </summary>
        internal static string FinalStatesCountNotEqualUseCaseCount {
            get {
                return ResourceManager.GetString("FinalStatesCountNotEqualUseCaseCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} transition doesn&apos;t have {1} use case name defined, which was set by business logic.
        /// </summary>
        internal static string TransitionHasNoRequiredUseCaseNameAttribute {
            get {
                return ResourceManager.GetString("TransitionHasNoRequiredUseCaseNameAttribute", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type &quot;{0}&quot; not found in &quot;{1}&quot; software layer for the following request metadata: use case &quot;{2}&quot;, transition &quot;{3}&quot;, and state &quot;{4}&quot;.
        /// </summary>
        internal static string TypeNotFound {
            get {
                return ResourceManager.GetString("TypeNotFound", resourceCulture);
            }
        }
    }
}
