<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SkySoft.Communication\SkySoft.Communication.csproj" />
    <ProjectReference Include="..\SkySoft.Core\SkySoft.Core.csproj" />
    <ProjectReference Include="..\SkySoft.IBPPApplication\SkySoft.IBPPApplication.csproj" />
  </ItemGroup>

</Project>
