<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\SkySoftFramework\SkySoft.APIHost.DPL\SkySoft.APIHost.DPL.csproj" />
    <ProjectReference Include="..\BPP.Person.DALCFG\BPP.Person.DALCFG.csproj" />
  </ItemGroup>

</Project>
