<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Content Remove="DnsRecords.json" />
  </ItemGroup>

  <ItemGroup>
    <None Include="DnsRecords.json">
      <CopyToOutputDirectory>Always</CopyToOutputDirectory>
    </None>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SkySoft.APIHost\SkySoft.APIHost.csproj" />
    <ProjectReference Include="..\SkySoft.Net.DnsServerConfiguration\SkySoft.Net.DnsServerConfiguration.csproj" />
  </ItemGroup>

</Project>
