<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SkySoft.APIHost.CON\SkySoft.APIHost.CON.csproj" />
    <ProjectReference Include="..\SkySoft.BPPApplication\SkySoft.BPPApplication.csproj" />
    <ProjectReference Include="..\SkySoft.DnsClient.CON\SkySoft.DnsClient.CON.csproj" />
    <ProjectReference Include="..\SkySoft.DnsServer.CON\SkySoft.DnsServer.CON.csproj" />
  </ItemGroup>

</Project>
