<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <OutputType>Library</OutputType>
    <NoDefaultLaunchSettingsFile>true</NoDefaultLaunchSettingsFile>
    <StaticWebAssetsEnabled>false</StaticWebAssetsEnabled>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SkySoft.APIHost.BLCFG\SkySoft.APIHost.BLCFG.csproj" />
    <ProjectReference Include="..\SkySoft.APIHost.DALCFG\SkySoft.APIHost.DALCFG.csproj" />
    <ProjectReference Include="..\SkySoft.APIHost.DPLCFG\SkySoft.APIHost.DPLCFG.csproj" />
    <ProjectReference Include="..\SkySoft.APIHostApp.BLCFG\SkySoft.APIHostApp.BLCFG.csproj" />
    <ProjectReference Include="..\SkySoft.APIHostApp.DPLCFG\SkySoft.APIHostApp.DPLCFG.csproj" />
    <ProjectReference Include="..\SkySoft.BPPApplication.CFG\SkySoft.BPPApplication.CFG.csproj" />
    <ProjectReference Include="..\SkySoft.DnsClient.DPLCFG\SkySoft.DnsClient.DPLCFG.csproj" />
    <ProjectReference Include="..\SkySoft.DnsClientApp.DPLCFG\SkySoft.DnsClientApp.DPLCFG.csproj" />
    <ProjectReference Include="..\SkySoft.Http.CFG\SkySoft.Http.CFG.csproj" />
    <ProjectReference Include="..\SkySoft.Logging.CFG\SkySoft.Logging.CFG.csproj" />
  </ItemGroup>

</Project>
