<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <DebugSymbols>true</DebugSymbols>
    <DebugType>embedded</DebugType>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TargetFramework>net9.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SkySoft.ILogging\SkySoft.ILogging.csproj" />
  </ItemGroup>

</Project>
