<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <OutputType>Library</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\SkySoftFramework\SkySoft.APIHost.CON\SkySoft.APIHost.CON.csproj" />
    <ProjectReference Include="..\..\SkySoftFramework\SkySoft.APIHost.DAL\SkySoft.APIHost.DAL.csproj" />
    <ProjectReference Include="..\..\SkySoftFramework\SkySoft.APIHost.INT\SkySoft.APIHost.INT.csproj" />
    <ProjectReference Include="..\..\SkySoftFramework\SkySoft.Contracts\SkySoft.Contracts.csproj" />
    <ProjectReference Include="..\..\SkySoftFramework\SkySoft.IBPPApplication\SkySoft.IBPPApplication.csproj" />
    <ProjectReference Include="..\..\SkySoftFramework\SkySoft.OperatingSystem\SkySoft.OperatingSystem.csproj" />
    <ProjectReference Include="..\BPP.Person.CON\BPP.Person.CON.csproj" />
  </ItemGroup>

</Project>
