trigger: none

pool:
  vmImage: 'windows-latest'

variables:
- group: sky-soft-application-server-dev

steps:
- powershell: ./pipelines/scripts/powershell/Increase_Version_Number.ps1
  displayName: 'increase package version'

- script: |
    echo nuget_package_version: $(nuget_package_version)
  displayName: 'display version variable'

- task: MorenoBruschi.manage-variable-group-task.custom-build-release-task.ManageVariableGroupTask@0
  displayName: 'update variable in variable group'
  inputs:
    pat: $(mvgt_pat)
    project: $(mvgt_bpp_project_id)
    vgname: $(mvgt_variable_group)
    orgname: $(mvgt_organization)
    op: Update
    varops: |
      = nuget_package_version => $(nuget_package_version)
