trigger: none

pool:
  vmImage: 'windows-latest'

variables:
- group: sky-soft-application-server-dev

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '20.x'
  displayName: 'install node.js'

- script: |
    cd ./pipelines/scripts/node-js
    npm install
  displayName: 'npm install'

- script: node ./pipelines/scripts/node-js/increase-version-number.js
  displayName: 'increase package version'

- script: |
    echo nuget_package_version: $(nuget_package_version)
  displayName: 'display version variable'

- task: MorenoBruschi.manage-variable-group-task.custom-build-release-task.ManageVariableGroupTask@0
  displayName: 'update variable in variable group'
  inputs:
    pat: $(mvgt_pat)
    project: $(mvgt_bpp_project_id)
    vgname: $(mvgt_variable_group)
    orgname: $(mvgt_organization)
    op: Update
    varops: |
      = nuget_package_version => $(nuget_package_version)
