trigger: none

pool:
  vmImage: 'windows-latest'

variables:
- group: sky-soft-application-server-dev
- name: ssas_project_path
  value: .\SkySoftFramework\SkySoft.ApplicationServer.Assembly\SkySoft.ApplicationServer.Assembly.csproj
- name: ssas_solution_path
  value: .\SkySoftFrameworkSolutions\SkySoftApplicationServerSolution.sln

steps:
- script: |
    echo build_config:                      $(build_config)
    echo nuget_enable_legacy_csproj_pack:   $(nuget_enable_legacy_csproj_pack)
    echo ssas_nuget_feed_name:              $(ssas_nuget_feed_name)
    echo ssas_nuget_package_version:        $(ssas_nuget_package_version)
    echo ssas_project_path:                 $(ssas_project_path)

  displayName: Display pipeline variables

- task: DotNetCoreCLI@2
  displayName: 'dotnet restore'
  inputs:
    command: 'restore'
    projects: $(ssas_project_path)

- task: DotNetCoreCLI@2
  displayName: 'dotnet build $(build_config)'
  inputs:
    command: 'build'
    projects: $(ssas_project_path)
    arguments: '--configuration $(build_config)'
    #arguments: '--configuration $(build_config) --output $(Build.ArtifactStagingDirectory)'

    # - task: DotNetCoreCLI@2
    #   displayName: 'dotnet pack'
    #   inputs:
    #     command: 'pack'
    #     packagesToPack: $(ssas_solution_path)
    #     versioningScheme: byEnvVar
    #     versionEnvVar: SSAS_NUGET_PACKAGE_VERSION
    #     outputDir: '$(System.DefaultWorkingDirectory)\..\n'

- script: >
    nuget pack $(ssas_project_path) -Version $(SSAS_NUGET_PACKAGE_VERSION) -OutputDirectory $(Pipeline.Workspace)\n -IncludeReferencedProjects

  displayName: "nuget pack"

- task: DotNetCoreCLI@2
  displayName: 'dotnet push'
  inputs:
    command: 'push'
    searchPatternPush: '$(Pipeline.Workspace)\n\*.nupkg'
    feedPublish: $(ssas_nuget_feed_name)
    # - script: |
    #     cd $(Pipeline.Workspace)
    #     dir
    #     cd $(Pipeline.Workspace)\n   
    #     dir
    #   displayName: "Debug: show folders content"
