parameters:
- name: build_config
  displayName: Build configuration
  type: string
  default: debug
  values:
  - debug
  - release

trigger: none

pool:
  vmImage: 'windows-latest'

variables:
  ssas_project_path: .\SkySoftFramework\SkySoft.ApplicationServer.Assembly\SkySoft.ApplicationServer.Assembly.csproj

steps:
- task: DotNetCoreCLI@2
  displayName: 'dotnet restore'
  inputs:
    command: 'restore'
    projects: $(ssas_project_path)

- task: DotNetCoreCLI@2
  displayName: 'dotnet build ${{ build_config }}'
  inputs:
    command: 'build'
    projects: $(ssas_project_path)
    arguments: '--configuration ${{ build_config }}'
