trigger: none

pool:
  vmImage: 'windows-latest'

variables:
- group: sky-soft-application-server-dev
- name: ssas_project_path
  value: .\SkySoftFramework\SkySoft.Http\SkySoft.Http.csproj

steps:
- script: |
    echo build_config:                      $(build_config)
    echo ssas_nuget_feed_name:              $(ssas_nuget_feed_name)
    echo ssas_nuget_package_version:        $(ssas_nuget_package_version)    
  displayName: Display pipeline variables

- task: DotNetCoreCLI@2
  displayName: 'dotnet restore'
  inputs:
    command: 'restore'
    projects: $(ssas_project_path)

- task: DotNetCoreCLI@2
  displayName: 'dotnet build $(build_config)'
  inputs:
    command: 'build'
    projects: $(ssas_project_path)
    arguments: '--configuration $(build_config) --no-restore'

# - task: DotNetCoreCLI@2
#   displayName: 'dotnet pack'
#   inputs:
#     command: 'pack'
#     packagesToPack: $(ssas_project_path)
#     versioningScheme: byEnvVar
#     versionEnvVar: SSAS_NUGET_PACKAGE_VERSION
#     outputDir: '$(Pipeline.Workspace)\n'
#     includesymbols: true

- script: |
    dotnet pack $(ssas_project_path) --output $(SSAS_NUGET_PACKAGE_VERSION) --include-symbols -p:SymbolPackageFormat=snupkg -p:PackageVersion=1.0.10    

- script: |
    cd $(Pipeline.Workspace)\n   
    dir
  displayName: "Debug: Show n folder"

- task: DotNetCoreCLI@2
  displayName: 'dotnet push'
  inputs:
    command: 'push'
    searchPatternPush: '$(Pipeline.Workspace)\n\*.nupkg'
    feedPublish: $(ssas_nuget_feed_name)
