<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SkySoft.BPPApplication\SkySoft.BPPApplication.csproj" />
    <ProjectReference Include="..\SkySoft.Contracts\SkySoft.Contracts.csproj" />
    <ProjectReference Include="..\SkySoft.DnsRecord.DTO\SkySoft.DnsRecord.DTO.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="Activities\ApplicationConfiguration\" />
  </ItemGroup>

</Project>
