<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <DebugSymbols>true</DebugSymbols>
    <DebugType>embedded</DebugType>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TargetFramework>net9.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\SkySoftFramework\SkySoft.BPPApplication\SkySoft.BPPApplication.csproj" />
    <ProjectReference Include="..\BPP.Person.CON\BPP.Person.CON.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="EventHandlers\" />
  </ItemGroup>

</Project>
