<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <DebugSymbols>true</DebugSymbols>
    <DebugType>embedded</DebugType>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <TargetFramework>net9.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Extensions.Configuration.Abstractions" Version="9.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\SkySoft.Core\SkySoft.Core.csproj" />
    <ProjectReference Include="..\SkySoft.ICommunication\SkySoft.ICommunication.csproj" />
    <ProjectReference Include="..\SkySoft.ILogging\SkySoft.ILogging.csproj" />
  </ItemGroup>

</Project>
