<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <DebugSymbols>true</DebugSymbols>
    <DebugType>embedded</DebugType>
    <ImplicitUsings>enable</ImplicitUsings>
    <IsPackable>true</IsPackable>
    <Nullable>enable</Nullable>
    <TargetFramework>net9.0</TargetFramework>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\..\SkySoftFramework\SkySoft.ApplicationServer.CFG\SkySoft.ApplicationServer.CFG.csproj" />
    <ProjectReference Include="..\..\SkySoftFramework\SkySoft.ApplicationServer.Runtime\SkySoft.ApplicationServer.Runtime.csproj" />
    <ProjectReference Include="..\BPP.Person.DPLCFG\BPP.Person.DPLCFG.csproj" />
    <ProjectReference Include="..\BPP.PersonApp.DPLCFG\BPP.PersonApp.DPLCFG.csproj" />
  </ItemGroup>

</Project>
