<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SkySoft.APIHost.CON\SkySoft.APIHost.CON.csproj" />
    <ProjectReference Include="..\SkySoft.APIHost.DPLCFG\SkySoft.APIHost.DPLCFG.csproj" />
    <ProjectReference Include="..\SkySoft.APIHost.DPL\SkySoft.APIHost.DPL.csproj" />
    <ProjectReference Include="..\SkySoft.APIHost.INI\SkySoft.APIHost.INI.csproj" />
    <ProjectReference Include="..\SkySoft.ApplicationServer.CFG\SkySoft.ApplicationServer.CFG.csproj" />
    <ProjectReference Include="..\SkySoft.ApplicationServer.Runtime\SkySoft.ApplicationServer.Runtime.csproj" />
    <ProjectReference Include="..\SkySoft.BPPApplication.CFG\SkySoft.BPPApplication.CFG.csproj" />
    <ProjectReference Include="..\SkySoft.BPPApplication\SkySoft.BPPApplication.csproj" />
    <ProjectReference Include="..\SkySoft.Communication\SkySoft.Communication.csproj" />
    <ProjectReference Include="..\SkySoft.Contracts\SkySoft.Contracts.csproj" />
    <ProjectReference Include="..\SkySoft.Core\SkySoft.Core.csproj" />
    <ProjectReference Include="..\SkySoft.DnsClient.CON\SkySoft.DnsClient.CON.csproj" />
    <ProjectReference Include="..\SkySoft.DnsClient.DPLCFG\SkySoft.DnsClient.DPLCFG.csproj" />
    <ProjectReference Include="..\SkySoft.DnsClient.DPL\SkySoft.DnsClient.DPL.csproj" />
    <ProjectReference Include="..\SkySoft.DnsClientApp.CON\SkySoft.DnsClientApp.CON.csproj" />
    <ProjectReference Include="..\SkySoft.DnsClientApp.DPLCFG\SkySoft.DnsClientApp.DPLCFG.csproj" />
    <ProjectReference Include="..\SkySoft.DnsClientApp.DPL\SkySoft.DnsClientApp.DPL.csproj" />
    <ProjectReference Include="..\SkySoft.DnsClientServerComponents\SkySoft.DnsClientServerComponents.csproj" />
    <ProjectReference Include="..\SkySoft.DnsRecord.DTI\SkySoft.DnsRecord.DTI.csproj" />
    <ProjectReference Include="..\SkySoft.DnsRecord.DTO\SkySoft.DnsRecord.DTO.csproj" />
    <ProjectReference Include="..\SkySoft.DnsServer.CON\SkySoft.DnsServer.CON.csproj" />
    <ProjectReference Include="..\SkySoft.Http.CFG\SkySoft.Http.CFG.csproj" />
    <ProjectReference Include="..\SkySoft.Http.DRV\SkySoft.Http.DRV.csproj" />
    <ProjectReference Include="..\SkySoft.Http\SkySoft.Http.csproj" />
    <ProjectReference Include="..\SkySoft.IBPPApplication\SkySoft.IBPPApplication.csproj" />
    <ProjectReference Include="..\SkySoft.ICommunication\SkySoft.ICommunication.csproj" />
  </ItemGroup>

</Project>
