<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net9.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <OutputType>Library</OutputType>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\SkySoft.APIHost.CON\SkySoft.APIHost.CON.csproj" />
    <ProjectReference Include="..\SkySoft.APIHost.INT\SkySoft.APIHost.INT.csproj" />
    <ProjectReference Include="..\SkySoft.DnsServer.DAL\SkySoft.DnsServer.DAL.csproj" />
    <ProjectReference Include="..\SkySoft.IBPPApplication\SkySoft.IBPPApplication.csproj" />
  </ItemGroup>

</Project>
