name: publish-nuget-packages

on:
  workflow_dispatch:
  push:
    branches: [ github-nuget-dev, github-nuget-prod ]

jobs:
  publish-nuget-packages:
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/github-nuget-dev' && 'dev' || github.ref == 'refs/heads/github-nuget-prod' && 'prod' }}

    steps:
    - name: show pipeline variables
      run: |
        echo bpp_code_pat:                ${{ secrets.bpp_code_pat }}
        echo bpp_code_publish_nuget_pat:  ${{ secrets.bpp_code_publish_nuget_pat }}
        echo build_config:                ${{ vars.build_config }}
        echo nuget_feed_name:             ${{ vars.nuget_feed_name }}
        echo nuget_package_version:       ${{ vars.nuget_package_version }}
        echo solution_path:               ${{ vars.solution_path }}

    - name: checkout branch ${{ github.ref_name }}
      uses: actions/checkout@v4

    - name: setup .net sdk
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'

    - name: dotnet restore
      run: dotnet restore ${{ vars.solution_path }}

    - name: dotnet build ${{ vars.build_config }}
      run: dotnet build ${{ vars.solution_path }} --configuration ${{ vars.build_config }} --no-restore 

    - name: dotnet pack
      run: |
        dotnet pack ${{ vars.solution_path }} \
          --configuration ${{ vars.build_config }} \
          --output ${{ github.workspace }}/n \
          -p:PackageVersion=${{ vars.nuget_package_version }} \
          --no-build \
          --no-restore
        
    - name: show packages folder
      run: |
        cd ${{ github.workspace }}/n
        ls

    - name: publish to github packages
      run: |
        dotnet nuget push "./n/*.nupkg" \
          --source "https://nuget.pkg.github.com/${{ github.repository }}/index.json" \
          --api-key "${{ secrets.GITHUB_TOKEN }}"

# https://nuget.pkg.github.com/dlaskarzhevsky/index.json
# --api-key "${{ secrets.bpp_code_publish_nuget_pat }}"

    # - name: update pipeline variable
    #   run: |
    #     curl -L "https://api.github.com/repos/dlaskarzhevsky/bpp-code/environments/prod/variables/nuget_package_version" `
    #       -X PATCH `
    #       -H "Accept: application/vnd.github+json" `
    #       -H "Authorization: Bearer ${{ secrets.BPP_CODE_PAT }}" `
    #       -d '{"name":"nuget_package_version","value":"1.0.2"}'
