name: publish-nuget-packages

on:
  push:
    branches: [ github-nuget-dev, github-nuget-prod ]

jobs:
  publish-nuget-packages:
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/github-nuget-dev' && 'dev' || github.ref == 'refs/heads/github-nuget-prod' && 'prod' }}

    steps:
    - name: show workflow variables
      run: |
        echo bpp_code_pat:                ${{ secrets.bpp_code_pat }}
        echo bpp_code_publish_nuget_pat:  ${{ secrets.bpp_code_publish_nuget_pat }}
        echo build_config:                ${{ vars.build_config }}
        echo nuget_feed_name:             ${{ vars.nuget_feed_name }}
        echo nuget_package_version:       ${{ vars.nuget_package_version }}
        echo solution_path:               ${{ vars.solution_path }}

    - name: checkout branch ${{ github.ref_name }}
      uses: actions/checkout@v4

    - name: setup .net sdk
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '9.0.x'

    - name: dotnet restore
      run: dotnet restore ${{ vars.solution_path }}

    - name: dotnet build ${{ vars.build_config }}
      run: dotnet build ${{ vars.solution_path }} --configuration ${{ vars.build_config }} --no-restore 

    - name: dotnet pack
      run: |
        dotnet pack ${{ vars.solution_path }} \
          --configuration ${{ vars.build_config }} \
          --output ${{ github.workspace }}/n \
          -p:PackageVersion=${{ vars.nuget_package_version }} \
          --no-build \
          --no-restore
        
    - name: show packages folder
      run: |
        cd ${{ github.workspace }}/n
        ls

    - name: publish to github packages
      run: |
        dotnet nuget push "./n/*.nupkg" \
          --source "https://nuget.pkg.github.com/${{ github.repository_owner }}/index.json" \
          --api-key "${{ secrets.bpp_code_publish_nuget_pat }}"

    - name: increase package version
      shell: pwsh
      run: ./Pipelines/scripts/Increase_Version_Number_GitHub.ps1 -nugetPackageVersion ${{ vars.nuget_package_version }}

    - name: show package version
      run: echo "nuget_package_version ${{ env.nuget_package_version }}"

    - name: show environment name
      run: |
        echo "The environment is $GITHUB_ENVIRONMENT"
        echo "The environment is ${{ env.GITHUB_ENVIRONMENT }}"
        echo "The environment is ${{ vars.GITHUB_ENVIRONMENT }}"
        echo "The environment is ${{ github.environment }}"

    - name: update workflow variable
      run: |
        curl -L "https://api.github.com/repos/${{ github.repository }}/environments/dev/variables/nuget_package_version" \
          -X PATCH \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ secrets.bpp_code_pat }}" \
          -d '{"name":"nuget_package_version","value":"${{ env.nuget_package_version }}"}'


    # - name: show current folder
    #   shell: pwsh
    #   run: Get-Location

    # - name: show script folder
    #   run: |
    #     cd ${{ github.workspace }}/Pipelines/scripts
    #     ls